"""Conversation sparks — caregiver prompts generated by LMD creative leaps.

When a caregiver is in a visit and the conversation stalls, MemoryLane
can offer them a "spark": a suggested angle combining two or three of
the patient's own memories in a way the caregiver might not have
thought of. The underlying mechanism is LMD's creative leap engine —
we feed it embeddings of two or three memories and ask for an
ORTHOGONAL (independent axes), ANALOGICAL (transferred pattern), or
EXTRAPOLATION (beyond known territory) leap. We then wrap the
resulting vector in a short caregiver-facing prompt.

Design principles:
  - Sparks are *prompts for the caregiver*, not scripts for the patient.
    The caregiver knows the person — they adapt the angle.
  - Only safe memories feed sparks. Distressing-flagged and
    DIFFICULT-toned memories never appear.
  - Every spark shows its sources. The caregiver should always be able
    to understand why the spark came up — no black-box suggestions.
  - Fails gracefully offline. If sentence-transformers isn't installed,
    we still produce sparks using a smaller, deterministic algorithm
    so the feature works in any environment.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Sequence

from sqlalchemy.orm import Session

from . import service
from .lmd_bridge import LMDBridge
from .models import EmotionalTone, Memory

# Leap-type → caregiver-facing framing. The creative leap engine tells us
# what KIND of connection it found; we turn that into a human instruction
# the caregiver can adapt on the spot.
_ANGLES = {
    "ANALOGICAL": "These memories share a pattern. Ask: \"When else in your life did something feel like this?\"",
    "ORTHOGONAL": "These are independent threads of your life. Ask: \"How did these parts of your life come together for you?\"",
    "EXTRAPOLATION": "Ask the patient to imagine a moment that combines these themes. \"If {a} had happened in the world of {b}, what would it have looked like?\"",
    "DIFFUSION": "These memories are near-neighbours. Ask what bridged them — \"Was there something that carried you from one to the other?\"",
    "GRAFT": "Take one piece of {a} and try it against {b}: \"Was there ever a version of {b} that felt like {a}?\"",
}

_DEFAULT_ANGLE = "Ask about the thread that connects these memories."


@dataclass
class ConversationSpark:
    """A single caregiver prompt."""

    suggested_angle: str
    source_memory_ids: list[str]
    source_memory_titles: list[str]
    leap_type: str
    novelty: float


def _safe_memories(memories: Sequence[Memory]) -> list[Memory]:
    return [
        m
        for m in memories
        if not m.flagged_distressing and m.tone != EmotionalTone.DIFFICULT
    ]


def _format_angle(template: str, titles: list[str]) -> str:
    """Fill {a}/{b} placeholders with the first two source titles (if present)."""
    a = titles[0] if len(titles) >= 1 else ""
    b = titles[1] if len(titles) >= 2 else titles[0] if titles else ""
    return template.replace("{a}", a).replace("{b}", b)


def _lmd_available() -> bool:
    try:
        from lmd import CreativeLeapConfig, CreativeLeapEngine  # noqa: F401

        return True
    except Exception:
        return False


def _spark_via_lmd(
    bridge: LMDBridge,
    pool: list[Memory],
    seed: random.Random,
) -> ConversationSpark | None:
    """Build a single spark using LMD's CreativeLeapEngine.

    Picks 2-3 memories, encodes them, generates a leap, and returns a
    caregiver-facing prompt. None if something in the LMD pipeline
    raises — callers fall through to the offline variant.
    """
    try:
        from lmd import CreativeLeapConfig, CreativeLeapEngine
    except Exception:
        return None

    k = min(len(pool), 3 if seed.random() > 0.4 else 2)
    sample = seed.sample(pool, k)
    embeddings = [bridge.encode(f"{m.title}. {m.description}") for m in sample]

    config = CreativeLeapConfig(content_dim=bridge.capabilities.embedding_dim)
    engine = CreativeLeapEngine(config)
    try:
        leap = engine.leap(embeddings, dopamine=0.7)
    except Exception:
        return None

    leap_name = leap.leap_type.name
    template = _ANGLES.get(leap_name, _DEFAULT_ANGLE)
    titles = [m.title for m in sample]
    return ConversationSpark(
        suggested_angle=_format_angle(template, titles),
        source_memory_ids=[m.id for m in sample],
        source_memory_titles=titles,
        leap_type=leap_name,
        novelty=round(float(leap.novelty), 3),
    )


def _offline_spark(pool: list[Memory], seed: random.Random) -> ConversationSpark:
    """Fallback when LMD's engine isn't available or fails.

    Still useful — pairs distant (by era + tone) memories and offers a
    generic analogical prompt. The sparks are less novel but the feature
    still works.
    """
    k = min(len(pool), 2)
    sample = seed.sample(pool, k)
    titles = [m.title for m in sample]
    template = _ANGLES["ANALOGICAL"]
    return ConversationSpark(
        suggested_angle=_format_angle(template, titles),
        source_memory_ids=[m.id for m in sample],
        source_memory_titles=titles,
        leap_type="offline_pairwise",
        novelty=0.4,
    )


def generate_sparks(
    db: Session,
    patient_id: str,
    n: int = 3,
    *,
    bridge: LMDBridge | None = None,
    rng_seed: int | None = None,
) -> list[ConversationSpark]:
    """Return up to `n` conversation sparks for the patient.

    Args:
        db: SQLAlchemy session.
        patient_id: Which patient's archive to draw from.
        n: Target spark count (1-10 typical).
        bridge: Optional pre-warmed LMDBridge (saves the MiniLM load
            when calling this repeatedly).
        rng_seed: Deterministic seed for tests.

    Returns an empty list if the patient has fewer than two safe
    memories — can't spark a connection from a single point.
    """
    all_memories = service.list_memories(db, patient_id)
    pool = _safe_memories(all_memories)
    if len(pool) < 2:
        return []

    active_bridge = bridge or LMDBridge(use_language_grounding=_lmd_available())
    seed = random.Random(rng_seed)

    sparks: list[ConversationSpark] = []
    # Guard against infinite loops — give up after a few failed attempts per
    # target spark. Sampling the same pool with a deterministic RNG means
    # deduping on source-set is the right signal.
    seen_sources: set[tuple[str, ...]] = set()
    attempts = 0
    while len(sparks) < n and attempts < n * 4:
        attempts += 1
        spark = _spark_via_lmd(active_bridge, pool, seed) if _lmd_available() else None
        if spark is None:
            spark = _offline_spark(pool, seed)

        key = tuple(sorted(spark.source_memory_ids))
        if key in seen_sources:
            continue
        seen_sources.add(key)
        sparks.append(spark)

    return sparks
